import { afterAll, describe, expect, test } from "bun:test";
import { symlink } from "node:fs/promises";
import { join } from "node:path";
import { checkProject } from "../src/check/check";
import { extractPattern, saveExtractedPattern } from "../src/extract/extract";
import { normalizeStem, scanNaming } from "../src/extract/naming";
import { parsePatternDocument, serializePatternDocument } from "../src/pattern/document";
import { collectInventory } from "../src/tree/inventory";
import { cleanupTempRoots, freshStore, repo } from "./support";

afterAll(cleanupTempRoots);

describe("inventory", () => {
  test("applies gitignore, deny lists, and the generated-code filter", async () => {
    const root = await repo({
      ".gitignore": "ignored.txt\nsecret/\n",
      "ignored.txt": "nope",
      "secret/inner.txt": "nope",
      "src/index.ts": "export {};",
      "node_modules/dep/index.js": "nope",
      "dist/out.js": "nope",
      "bun.lock": "{}",
      "src/generated.ts": "// @generated by protoc\nexport {};",
    });
    const inventory = await collectInventory(root);
    const paths = inventory.files.map((f) => f.path);
    expect(paths).toEqual([".gitignore", "src/index.ts"]);
    expect(inventory.denied).toContain("node_modules");
    expect(inventory.denied).toContain("dist");
  });

  test.skipIf(process.platform === "win32")("skips symlinks entirely", async () => {
    const root = await repo({ "real.ts": "export {};" });
    await symlink(join(root, "real.ts"), join(root, "link.ts"));
    const inventory = await collectInventory(root);
    expect(inventory.files.map((f) => f.path)).toEqual(["real.ts"]);
  });
});

describe("naming scanner", () => {
  test("votes a kebab-case convention and a PascalCase .tsx override", async () => {
    const root = await repo({
      "src/user-service.ts": "",
      "src/order-service.ts": "",
      "src/api-client.ts": "",
      "src/data-store.ts": "",
      "src/event-bus.ts": "",
      "src/components/UserCard.tsx": "",
      "src/components/OrderList.tsx": "",
      "src/components/AppShell.tsx": "",
      "src/components/NavBar.tsx": "",
      "src/components/PageFooter.tsx": "",
    });
    const { naming } = scanNaming(await collectInventory(root));
    expect(naming?.files).toBeUndefined(); // mixed globally: kebab + Pascal
    expect(naming?.extensions[".ts"]).toBe("kebab-case");
    expect(naming?.extensions[".tsx"]).toBe("PascalCase");
  });

  test("degrades a mixed convention to a counted note, never a facet", async () => {
    const root = await repo({
      "a-b.py": "",
      "c-d.py": "",
      "e_f.py": "",
      "g_h.py": "",
      "i_j.py": "",
      "k-l.py": "",
    });
    const scan = scanNaming(await collectInventory(root));
    expect(scan.naming).toBeUndefined();
    expect(scan.notes.join("\n")).toContain("mixed");
  });

  test("a facet must cover the names that abstained, since check judges every one", async () => {
    // Five PascalCase components against twelve single-word modules: the
    // distinctive names agree on PascalCase, but check would flag every
    // module, so the pattern must not say it.
    const modules = [
      "fit",
      "check",
      "store",
      "learn",
      "serve",
      "export",
      "extract",
      "naming",
      "layout",
      "schema",
      "bundle",
      "brief",
    ];
    const root = await repo({
      "src/App.vue": "",
      "src/LibraryView.vue": "",
      "src/PatternView.vue": "",
      "src/CheckView.vue": "",
      "src/FitView.vue": "",
      ...Object.fromEntries(modules.map((name) => [`src/${name}.ts`, "export {};\n"])),
    });
    const scan = scanNaming(await collectInventory(root));
    expect(scan.naming?.files).toBeUndefined();
    expect(scan.naming?.extensions[".vue"]).toBe("PascalCase");
    expect(scan.notes.join("\n")).toContain("lean PascalCase");

    const store = await freshStore();
    const { document } = await extractPattern(root, "abstainers");
    await store.save(document);
    const violations = (await checkProject(store, "abstainers", root)).violations;
    expect(violations.filter((v) => v.rule === "naming")).toEqual([]);
  });

  test("a small extension that always dissents is noted, with the override that settles it", async () => {
    // Thirteen snake_case Go files carry the vote over three kebab-case scripts.
    const go = [
      "index_byte",
      "read_line",
      "wide_char",
      "term_size",
      "key_map",
      "run_loop",
      "ansi_code",
      "term_info",
      "char_class",
      "byte_pool",
      "event_loop",
      "file_walk",
      "exit_code",
    ];
    const root = await repo({
      ...Object.fromEntries(go.map((name) => [`src/${name}.go`, ""])),
      "shell/key-bindings.fish": "",
      "shell/completion-examples.fish": "",
      "shell/key-bindings.zsh": "",
    });
    const scan = scanNaming(await collectInventory(root));
    expect(scan.naming?.files).toBe("snake_case");
    expect(scan.naming?.extensions).toEqual({});
    expect(scan.notes).toEqual([
      "2 .fish files (kebab-case where distinctive) do not follow the snake_case files convention, so check will report them; add a naming.extensions entry for .fish if that is intentional.",
      "1 .zsh file (kebab-case where distinctive) do not follow the snake_case files convention, so check will report them; add a naming.extensions entry for .zsh if that is intentional.",
    ]);
  });

  test("pytest's test_ prefix is idiom, not case, like Go's _test suffix", () => {
    expect(normalizeStem("test__detect_program_name")).toBe("detect_program_name");
    expect(normalizeStem("test_utils")).toBe("utils");
    expect(normalizeStem("testing")).toBe("testing");
    expect(normalizeStem("__init__")).toBe("init");
  });

  test("mandated names and .github wizard files never vote", async () => {
    const root = await repo({
      "README.md": "",
      Dockerfile: "",
      ".github/ISSUE_TEMPLATE/bug_report.yml": "",
      ".github/PULL_REQUEST_TEMPLATE.md": "",
      "index.ts": "",
    });
    const scan = scanNaming(await collectInventory(root));
    expect(scan.naming).toBeUndefined();
    expect(scan.notes).toEqual([]);
  });
});

describe("extract end to end", () => {
  const TS_CLI_REPO: Record<string, string> = {
    "README.md":
      "# widget\n\nA tidy command line tool for people who like tidy things. " +
      "It reads your files, checks them carefully, and prints a friendly report. " +
      "Install it with your favorite package manager and run it from the terminal. " +
      "The configuration lives next to your project and travels with your repository. " +
      "Contributions are welcome; please open an issue before sending large changes. " +
      "The checker walks the whole tree, applies every rule it knows about, and then " +
      "explains each finding in plain language so newcomers can fix things quickly. " +
      "Nothing leaves your machine: reports are written to standard output and the " +
      "tool has no network access at all, which keeps security reviews simple.",
    LICENSE: "MIT License\n",
    "package.json": JSON.stringify(
      {
        name: "widget",
        version: "1.0.0",
        engines: { node: ">=22" },
        scripts: { test: "bun test", lint: "biome check .", build: "bun build src/index.ts" },
        dependencies: { commander: "^12.0.0", zod: "^4.0.0", yaml: "^2.8.0" },
        devDependencies: { "@biomejs/biome": "^2.0.0", "left-pad": "^1.3.0" },
      },
      null,
      2,
    ),
    "biome.json": JSON.stringify({ formatter: { enabled: true }, linter: { enabled: true } }),
    "tsconfig.json": JSON.stringify({ compilerOptions: { strict: true } }),
    ".gitignore": "node_modules/\ndist/\n",
    "src/index.ts": "export {};\n",
    "src/commands/init.ts": "export {};\n",
    "src/commands/build.ts": "export {};\n",
    "src/commands/dev.ts": "export {};\n",
    "src/commands/check.ts": "export {};\n",
    "test/index.test.ts": "import {} from 'bun:test';\n",
  };

  test("a TypeScript CLI repo yields the pattern a human would write", async () => {
    const root = await repo(TS_CLI_REPO);
    const { document, files } = await extractPattern(root, "widget");
    const { pattern } = document;

    expect(pattern.languages?.programming[0]).toBe("TypeScript");
    expect(pattern.languages?.versions.node).toBe(">=22");
    expect(pattern.languages?.natural).toBe("en");
    expect(pattern.license).toBe("MIT"); // from the LICENSE text; no manifest field needed
    expect(pattern.commands).toEqual({
      build: "bun build src/index.ts",
      lint: "biome check .",
      test: "bun test",
    });
    expect(pattern.toolchain?.packageManager).toBeUndefined(); // no lockfile committed
    expect(pattern.toolchain?.formatter).toBe("biome");
    expect(pattern.toolchain?.linter).toBe("biome");
    expect(pattern.toolchain?.typechecker).toBe("tsc");
    expect(pattern.toolchain?.testRunner).toBe("bun-test");
    expect(pattern.dependencies?.runtime).toEqual({
      cli: "commander",
      serialization: "yaml",
      validation: "zod",
    });
    expect(pattern.dependencies?.dev).toEqual({ format: "biome", lint: "biome", typecheck: "tsc" });
    expect(pattern.dependencies?.versionPolicy).toBe("caret");
    expect(files["toolchain/biome.json"]).toBeDefined();

    const paths = pattern.layout.map((e) => e.path);
    expect(paths).toContain("src/commands/{name}.ts"); // file-per-resource convention
    expect(paths).toContain("README.md");
    expect(document.prose).toContain("left-pad"); // unknown dep degraded to prose
  });

  test("extraction is deterministic: same repo, byte-identical pattern", async () => {
    const root = await repo(TS_CLI_REPO);
    const first = serializePatternDocument((await extractPattern(root, "widget")).document);
    const second = serializePatternDocument((await extractPattern(root, "widget")).document);
    expect(second).toBe(first);
  });

  test("the extracted document round-trips through parse", async () => {
    const root = await repo(TS_CLI_REPO);
    const { document } = await extractPattern(root, "widget");
    const reparsed = parsePatternDocument(serializePatternDocument(document));
    expect(reparsed.pattern.name).toBe("widget");
  });

  test("a Python service repo extracts its own idioms", async () => {
    const root = await repo({
      "pyproject.toml": [
        "[project]",
        'name = "shepherd"',
        'requires-python = ">=3.12"',
        'dependencies = ["fastapi==0.111.0", "httpx==0.27.0", "sqlalchemy==2.0.30", "pydantic==2.7.0"]',
        "",
        "[dependency-groups]",
        'dev = ["pytest==8.2.0", "ruff==0.4.4"]',
        "",
        "[tool.ruff]",
        "line-length = 100",
        "",
        "[tool.pytest.ini_options]",
        'testpaths = ["tests"]',
      ].join("\n"),
      "app/main.py": "",
      "app/routers/users.py": "",
      "app/routers/items.py": "",
      "app/routers/orders.py": "",
      "tests/test_users.py": "",
      "uv.lock": "",
    });
    const { document, files } = await extractPattern(root, "shepherd");
    const { pattern } = document;

    expect(pattern.languages?.programming).toEqual(["Python"]);
    expect(pattern.languages?.versions.python).toBe(">=3.12");
    expect(pattern.toolchain?.packageManager).toBe("uv");
    expect(pattern.toolchain?.linter).toBe("ruff");
    expect(pattern.toolchain?.testRunner).toBe("pytest");
    expect(files["toolchain/pyproject.tool.ruff.toml"]).toContain("line-length");
    expect(pattern.dependencies?.runtime["web-framework"]).toBe("fastapi");
    expect(pattern.dependencies?.runtime["http-client"]).toBe("httpx");
    expect(pattern.dependencies?.dev.test).toBe("pytest");
    expect(pattern.dependencies?.versionPolicy).toBe("pinned");
    expect(pattern.layout.map((e) => e.path)).toContain("app/routers/{name}.py");
  });

  test("same-purpose conflicts degrade to prose instead of guessing", async () => {
    const root = await repo({
      "package.json": JSON.stringify({
        name: "torn",
        dependencies: { axios: "^1.0.0", ky: "^1.0.0" },
      }),
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "torn");
    expect(document.pattern.dependencies?.runtime["http-client"]).toBeUndefined();
    expect(document.prose).toContain("axios and ky");
  });

  test("workspace members generalize to a {name} template", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "mono", workspaces: ["packages/*"] }),
      "packages/api/package.json": JSON.stringify({ name: "@mono/api" }),
      "packages/api/src/index.ts": "",
      "packages/web/package.json": JSON.stringify({ name: "@mono/web" }),
      "packages/web/src/index.ts": "",
    });
    const { document } = await extractPattern(root, "mono");
    const paths = document.pattern.layout.map((e) => e.path);
    expect(paths).toContain("packages/{name}/");
    expect(paths).toContain("packages/{name}/package.json");
    expect(paths).toContain("packages/{name}/src/");
  });

  const WORKSPACE_REPO: Record<string, string> = {
    "package.json": JSON.stringify({ name: "acme", workspaces: ["packages/*"] }),
    "packages/api/package.json": JSON.stringify({ name: "@acme/api", version: "0.1.0" }),
    "packages/web/package.json": JSON.stringify({ name: "@acme/web", version: "0.1.0" }),
    "packages/api/tsconfig.json": '{ "extends": "../../tsconfig.json" }\n',
    "packages/web/tsconfig.json": '{ "extends": "../../tsconfig.json" }\n',
    "packages/api/src/index.ts": "export {};\n",
    "packages/web/src/index.ts": "export {};\n",
  };

  test("agreeing sibling files become templates with the name and scope placeheld", async () => {
    const { document, files } = await extractPattern(await repo(WORKSPACE_REPO), "acme");

    expect(document.pattern.scaffold?.templates).toEqual([
      "packages/{name}/package.json",
      "packages/{name}/src/index.ts",
      "packages/{name}/tsconfig.json",
    ]);
    expect(files["templates/packages/{name}/package.json"]).toContain('"@{{project}}/{{name}}"');
    expect(files["templates/packages/{name}/tsconfig.json"]).toBe(
      '{ "extends": "../../tsconfig.json" }\n',
    );
  });

  test("siblings that disagree are content, not a template", async () => {
    const { document } = await extractPattern(
      await repo({
        ...WORKSPACE_REPO,
        "packages/web/tsconfig.json": '{ "extends": "./base.json" }\n',
      }),
      "acme",
    );
    expect(document.pattern.scaffold?.templates).not.toContain("packages/{name}/tsconfig.json");
    expect(document.prose).toContain("packages/{name}/tsconfig.json differs across 2 siblings");
    expect(document.prose).toContain("largest agreeing group: 1");
  });

  test("files that already write {{ }} placeholders are never captured", async () => {
    const { document } = await extractPattern(
      await repo({
        ...WORKSPACE_REPO,
        "packages/api/tsconfig.json": "{{ handlebars }}\n",
        "packages/web/tsconfig.json": "{{ handlebars }}\n",
      }),
      "acme",
    );
    expect(document.pattern.scaffold?.templates).not.toContain("packages/{name}/tsconfig.json");
    expect(document.prose).toContain("already contains {{ }} placeholders");
  });

  test("saveExtractedPattern writes pattern.md plus captured configs", async () => {
    const root = await repo(TS_CLI_REPO);
    const store = await freshStore();

    await saveExtractedPattern(store, await extractPattern(root, "widget"));

    expect((await store.load("widget")).pattern.toolchain?.formatter).toBe("biome");
    expect(await Bun.file(join(store.dirOf("widget"), "toolchain", "biome.json")).exists()).toBe(
      true,
    );
  });

  test("re-extracting replaces the pattern wholesale; no stale captures linger", async () => {
    const store = await freshStore();
    const withBiome = await repo({
      ...TS_CLI_REPO,
    });
    await saveExtractedPattern(store, await extractPattern(withBiome, "widget"));
    expect(await Bun.file(join(store.dirOf("widget"), "toolchain", "biome.json")).exists()).toBe(
      true,
    );

    const { "biome.json": _dropped, ...withoutBiome } = TS_CLI_REPO;
    await saveExtractedPattern(store, await extractPattern(await repo(withoutBiome), "widget"));
    // The retired capture must not survive to ship inside exported bundles.
    expect(await Bun.file(join(store.dirOf("widget"), "toolchain", "biome.json")).exists()).toBe(
      false,
    );
  });

  test("a gitignored lockfile is not package-manager evidence (clone-state invariance)", async () => {
    const { document } = await extractPattern(
      await repo({
        "package.json": JSON.stringify({ name: "w", scripts: { test: "bun test" } }),
        ".gitignore": "bun.lock\n",
        "bun.lock": "{}",
        "src/index.ts": "export {};\n",
      }),
      "w",
    );
    expect(document.pattern.toolchain?.packageManager).toBeUndefined();
  });

  test("justfile recipes with parameters and deps are inventoried; assets are invisible", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "t" }),
      justfile:
        "set shell := ['bash', '-c']\n\nbuild target:\n  echo hi\n\ntest: build\n  echo t\n",
      "fonts/heavy.ttf": "\x00\x01fakefont",
      "src/index.ts": "export {};\n",
    });
    const { document } = await extractPattern(root, "t");
    expect(document.prose).toContain("justfile targets: build, test");
    expect(document.prose).not.toContain("unrecognized extensions");
  });

  test("commands keep only verbs that would run in a fresh project", async () => {
    const root = await repo({
      "package.json": JSON.stringify({
        name: "webby",
        scripts: {
          test: "vitest run",
          fmt: "prettier --write .",
          check: "npm run lint && npm run knip",
          lint: "eslint .",
          deploy: "wrangler deploy",
        },
        devDependencies: { vitest: "^3.0.0" },
      }),
      "src/index.ts": "export {};\n",
    });
    const { document } = await extractPattern(root, "webby");
    expect(document.pattern.commands).toEqual({
      format: "prettier --write .",
      lint: "eslint .",
      test: "vitest run",
    });
    expect(document.prose).toContain('"knip"'); // check degraded: it calls a non-canonical script
    expect(document.pattern.commands?.deploy).toBeUndefined(); // not a canonical verb
  });

  test("simple justfile recipes become commands; entangled ones degrade", async () => {
    const root = await repo({
      "Cargo.toml": '[package]\nname = "crab"\nversion = "0.1.0"\n',
      justfile: "test:\n  cargo test\n\nbuild target:\n  cargo build\n",
      "src/main.rs": "fn main() {}\n",
    });
    const { document } = await extractPattern(root, "crab");
    expect(document.pattern.toolchain?.taskRunner).toBe("just");
    expect(document.pattern.commands).toEqual({ test: "cargo test" });
    expect(document.prose).toContain('"build" recipe');
  });

  test("a license conflict between manifest and LICENSE yields a note, not a facet", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "torn", license: "Apache-2.0" }),
      LICENSE: "MIT License\n\nPermission is hereby granted, free of charge...\n",
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "torn");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain("Apache-2.0 but LICENSE reads like MIT");
  });

  test("simple Makefile recipes become commands with make as the runner", async () => {
    const root = await repo({
      "Cargo.toml": '[package]\nname = "mk"\nversion = "0.1.0"\n',
      Makefile: "test:\n\tcargo test\n\nbuild dep:\n\tcargo build\n",
      "src/main.rs": "fn main() {}\n",
    });
    const { document } = await extractPattern(root, "mk");
    expect(document.pattern.toolchain?.taskRunner).toBe("make");
    expect(document.pattern.commands).toEqual({ test: "cargo test" });
    expect(document.prose).toContain('"build" recipe');
  });

  test("quiet justfile recipes (@test:) still count", async () => {
    const root = await repo({
      "Cargo.toml": '[package]\nname = "hush"\nversion = "0.1.0"\n',
      justfile: "@test:\n  cargo test\n",
      "src/main.rs": "fn main() {}\n",
    });
    const { document } = await extractPattern(root, "hush");
    expect(document.pattern.commands).toEqual({ test: "cargo test" });
  });

  test("the 0BSD text does not fingerprint as ISC", async () => {
    const root = await repo({
      LICENSE:
        "Permission to use, copy, modify, and/or distribute this software for any " +
        "purpose with or without fee is hereby granted.\n\nTHE SOFTWARE IS PROVIDED " +
        '"AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE.\n',
      "main.py": "",
    });
    const { document } = await extractPattern(root, "zero-bsd");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain("notice-retention clause");
  });

  test("the GPL text degrades to a note naming both readings", async () => {
    const root = await repo({
      LICENSE: "GNU GENERAL PUBLIC LICENSE\nVersion 3, 29 June 2007\n",
      "main.py": "",
    });
    const { document } = await extractPattern(root, "gnu-ish");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain('"-only" from "-or-later"');
  });

  test("the MIT-0 text does not fingerprint as MIT", async () => {
    const root = await repo({
      LICENSE:
        "MIT No Attribution\n\nCopyright 2020 Someone\n\nPermission is hereby granted, free " +
        "of charge, to any person obtaining a copy of this software and associated " +
        'documentation files (the "Software"), to deal in the Software without restriction, ' +
        "and to permit persons to whom the Software is furnished to do so.\n",
      "main.py": "",
    });
    const { document } = await extractPattern(root, "mit-zero");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain("notice-retention clause");
  });

  test("assets and docs neither vote nor dissent: naming is about code", async () => {
    // Five kebab-case TS files against three PascalCase docs and an asset:
    // unscoped, the docs would drag the winner under the 80% bar and kill
    // the facet; scoped to the languages facet's extensions, code decides.
    const root = await repo({
      "src/data-model.ts": "export {};\n",
      "src/api-client.ts": "export {};\n",
      "src/user-store.ts": "export {};\n",
      "src/form-state.ts": "export {};\n",
      "src/view-model.ts": "export {};\n",
      "docs/DesignNotes.md": "# notes\n",
      "docs/MeetingLog.md": "# log\n",
      "docs/RoadMap.md": "# map\n",
      "docs/TeamPhoto.png": "not-a-real-png",
    });
    const { document } = await extractPattern(root, "scoped");
    expect(document.pattern.naming?.files).toBe("kebab-case");
  });

  test("the canonical MIT text fingerprints as MIT despite its title form and line wraps", async () => {
    // "The MIT License (MIT)" title, and the notice-retention clause wrapped
    // mid-phrase, both shapes real repos ship (this is how typer and
    // petite-vue read; the wrap once flipped plain MIT into an MIT-0 note).
    const root = await repo({
      LICENSE:
        "The MIT License (MIT)\n\nCopyright (c) 2020 Someone\n\nPermission is hereby granted, " +
        "free of charge, to any person obtaining a copy\nof this software and associated " +
        'documentation files (the "Software")...\n\nThe above copyright notice and this ' +
        "permission notice shall be included in\nall copies or substantial portions of the " +
        "Software.\n",
      "main.py": "",
    });
    const { document } = await extractPattern(root, "mit-wrapped");
    expect(document.pattern.license).toBe("MIT");
  });

  test("a manifest license that is not an SPDX id becomes a note, never a facet", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "closed", license: "Proprietary — all rights" }),
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "closed");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain("does not recognize as an SPDX id");
  });

  test("a recipe reading a taskfile variable is a note, not a command that cannot run", async () => {
    const root = await repo({
      justfile: 'bin := "./node_modules/.bin"\n\ntest:\n  {{bin}}/jest\n\nlint:\n  biome check .\n',
      "package.json": JSON.stringify({ name: "varsy" }),
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "varsy");
    expect(document.pattern.commands?.test).toBeUndefined();
    expect(document.pattern.commands?.lint).toBe("biome check .");
    expect(document.prose).toContain("reads a just variable");
  });

  test("an alias recipe never displaces the canonical verb, whatever the file order", async () => {
    const root = await repo({
      justfile: "format:\n  biome format .\n\nfmt:\n  echo stale\n",
      "package.json": JSON.stringify({ name: "aliased" }),
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "aliased");
    expect(document.pattern.commands?.format).toBe("biome format .");
  });

  test("a sibling file carrying an author's email is never captured as a template", async () => {
    const { document } = await extractPattern(
      await repo({
        ...WORKSPACE_REPO,
        "packages/api/package.json": JSON.stringify({
          name: "@acme/api",
          author: "Jane Doe <jane@acme-corp.example>",
        }),
        "packages/web/package.json": JSON.stringify({
          name: "@acme/web",
          author: "Jane Doe <jane@acme-corp.example>",
        }),
      }),
      "acme",
    );
    expect(document.pattern.scaffold?.templates).not.toContain("packages/{name}/package.json");
    expect(document.prose).toContain("an email address");
  });

  test("a sibling file naming the source project is never captured as a template", async () => {
    const { document } = await extractPattern(
      await repo({
        ...WORKSPACE_REPO,
        "packages/api/README.md": "# api\n\nPart of the acme platform.\n",
        "packages/web/README.md": "# web\n\nPart of the acme platform.\n",
      }),
      "acme",
    );
    expect(document.pattern.scaffold?.templates).not.toContain("packages/{name}/README.md");
    expect(document.prose).toContain('the source project\'s name ("acme")');
  });

  test("a manifest whose declaration dolly cannot use silences a stray LICENSE file", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "closed", license: "Proprietary — all rights" }),
      LICENSE: "MIT License\n\nCopyright (c) 2020 Someone\n",
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "closed");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain("the manifest's own declaration is what counts");
  });

  test("a manifest id conflicting with a GPL text the fingerprint cannot pin is still a conflict", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "torn-gpl", license: "MIT" }),
      LICENSE: "GNU GENERAL PUBLIC LICENSE\nVersion 3, 29 June 2007\n",
      "src/a.ts": "",
    });
    const { document } = await extractPattern(root, "torn-gpl");
    expect(document.pattern.license).toBeUndefined();
    expect(document.prose).toContain("MIT but LICENSE reads like GPL-3.0-only or GPL-3.0-or-later");
  });

  test("a GPL manifest agrees with the GPL text it disambiguates", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "gnu", license: "GPL-3.0-only" }),
      LICENSE: "GNU GENERAL PUBLIC LICENSE\nVersion 3, 29 June 2007\n",
      "src/a.ts": "",
    });
    expect((await extractPattern(root, "gnu")).document.pattern.license).toBe("GPL-3.0-only");
  });

  test("a dual-licensed crate's LICENSE-MIT and LICENSE-APACHE are license files, and its check is clean", async () => {
    const root = await repo({
      "Cargo.toml": '[package]\nname = "hf"\nversion = "1.0.0"\nlicense = "MIT OR Apache-2.0"\n',
      "LICENSE-APACHE":
        "                                 Apache License\n                           Version 2.0, January 2004\n",
      "LICENSE-MIT":
        "MIT License\n\nCopyright (c) 2026 hf\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\n",
      "src/main.rs": "fn main() {}\n",
    });
    const { document, files } = await extractPattern(root, "hf");
    expect(document.pattern.license).toBe("MIT OR Apache-2.0");
    const store = await freshStore();
    await saveExtractedPattern(store, { document, files });
    const report = await checkProject(store, "hf", root);
    expect(report.violations.filter((v) => v.rule === "license")).toEqual([]);
  });

  test("an SPDX expression agrees with a LICENSE carrying any one of its ids", async () => {
    const root = await repo({
      "package.json": JSON.stringify({ name: "dual", license: "(MIT OR Apache-2.0)" }),
      LICENSE: "MIT License\n\nCopyright (c) 2020 Someone\n",
      "src/a.ts": "",
    });
    expect((await extractPattern(root, "dual")).document.pattern.license).toBe(
      "(MIT OR Apache-2.0)",
    );
  });

  test("dropping a script also drops its callers, direct yarn invocations included", async () => {
    const root = await repo({
      "package.json": JSON.stringify({
        name: "chained",
        scripts: {
          test: "vitest run",
          check: "npm run lint", // orphaned when lint is dropped below
          lint: "npm run style", // style is not canonical, so lint is dropped
          style: "eslint .",
          build: "yarn compile", // direct yarn call, no `run`
          compile: "tsc -b",
        },
      }),
      "src/index.ts": "export {};\n",
    });
    const { document } = await extractPattern(root, "chained");
    expect(document.pattern.commands).toEqual({ test: "vitest run" });
    expect(document.prose).toContain('"lint"'); // check's note names what it ran
    expect(document.prose).toContain('"compile"');
  });

  test("a blank line inside a recipe body does not shrink it to one line", async () => {
    const root = await repo({
      "Cargo.toml": '[package]\nname = "gap"\nversion = "0.1.0"\n',
      Makefile: "build:\n\tcargo build\n\ntest:\n\tcargo fetch\n\n\tcargo test\n",
      "src/main.rs": "fn main() {}\n",
    });
    const { document } = await extractPattern(root, "gap");
    expect(document.pattern.commands).toEqual({ build: "cargo build" });
    expect(document.prose).toContain('"test" recipe');
  });

  test("dissent notes count the largest agreeing group, wherever it sits", async () => {
    const { document } = await extractPattern(
      await repo({
        "package.json": JSON.stringify({ name: "mono", workspaces: ["packages/*"] }),
        "packages/alpha/index.ts": "export const one = 1;\n",
        "packages/beta/index.ts": "export const two = 2;\n",
        "packages/gamma/index.ts": "export const two = 2;\n",
      }),
      "mono",
    );
    expect(document.prose).toContain("largest agreeing group: 2");
  });

  test("the identity gate knows the source project's name outside npm", async () => {
    const cargoMember = (name: string) =>
      `[package]\nname = "${name}"\nrepository = "https://github.com/acme/myproj"\n`;
    const { document } = await extractPattern(
      await repo({
        "Cargo.toml": '[package]\nname = "myproj"\nversion = "0.1.0"\n',
        "crates/alpha/Cargo.toml": cargoMember("alpha"),
        "crates/beta/Cargo.toml": cargoMember("beta"),
        "crates/gamma/Cargo.toml": cargoMember("gamma"),
        "crates/alpha/src/lib.rs": "pub fn hello() {}\n",
        "crates/beta/src/lib.rs": "pub fn hello() {}\n",
        "crates/gamma/src/lib.rs": "pub fn hello() {}\n",
        "src/main.rs": "fn main() {}\n",
      }),
      "myproj",
    );
    expect(document.pattern.scaffold?.templates ?? []).not.toContain("crates/{name}/Cargo.toml");
    expect(document.prose).toContain('the source project\'s name ("myproj")');
  });

  test("colocated tests vote a testing facet with their naming shape", async () => {
    const { document } = await extractPattern(
      await repo({
        "package.json": JSON.stringify({ name: "tested" }),
        "src/user.ts": "export {};\n",
        "src/user.test.ts": "",
        "src/order.ts": "export {};\n",
        "src/order.test.ts": "",
      }),
      "tested",
    );
    expect(document.pattern.testing).toEqual({
      placement: "colocated",
      filePattern: "{stem}.test.ts",
    });
  });

  test("tests split across placements degrade to a counted note", async () => {
    const { document } = await extractPattern(
      await repo({
        "package.json": JSON.stringify({ name: "torn-tests" }),
        "src/user.ts": "export {};\n",
        "src/user.test.ts": "",
        "tests/order.test.ts": "",
      }),
      "torn-tests",
    );
    expect(document.pattern.testing).toBeUndefined();
    expect(document.prose).toContain("split between separate (1) and colocated (1)");
  });

  test("a hook manager fingerprints into toolchain.hooks", async () => {
    const { document } = await extractPattern(
      await repo({
        "package.json": JSON.stringify({ name: "hooked" }),
        "lefthook.yml": "pre-commit:\n  commands:\n    lint:\n      run: biome check .\n",
        "src/a.ts": "",
      }),
      "hooked",
    );
    expect(document.pattern.toolchain?.hooks).toBe("lefthook");
    // The manager's config is captured like any other toolchain config, so
    // `new` writes it back and check can recreate it; the facet is no
    // longer a do-nothing loop.
    expect(document.pattern.toolchain?.configs["lefthook.yml"]).toBe("toolchain/lefthook.yml");
  });

  test("an empty directory extracts an empty but valid pattern", async () => {
    const root = await repo({ "notes.txt": "just a file" });
    const { document } = await extractPattern(root, "empty-ish");
    expect(document.pattern.name).toBe("empty-ish");
    expect(document.pattern.layout).toEqual([]);
    expect(() => parsePatternDocument(serializePatternDocument(document))).not.toThrow();
  });
});
