import { open, readdir } from "node:fs/promises";
import { join } from "node:path";
import ignore, { type Ignore } from "ignore";
import { readIfExists } from "./files";

/**
 * The shared file inventory every scanner reads (ADR-0003): one walk, one
 * deny policy, one generated-code filter, one deterministic order, so all
 * facets in one pattern rest on the same evidence.
 */
export interface Inventory {
  root: string;
  /** Surviving regular files, repo-relative POSIX paths, sorted. */
  files: InventoryFile[];
  /** Surviving directories, sorted. Vendored dirs appear here but not their contents. */
  dirs: string[];
  /** Vendored dirs (recorded, never descended). */
  vendored: string[];
  /** Dirs present on disk but excluded as build output / caches. */
  denied: string[];
  /** Lockfiles seen (package-manager evidence for toolchain; nothing else). */
  lockfiles: string[];
}

export interface InventoryFile {
  path: string;
  size: number;
}

/** Build output and caches: never evidence, even when committed. */
export const DENY_DIRS = new Set([
  ".git",
  "node_modules",
  ".venv",
  "venv",
  "__pycache__",
  ".mypy_cache",
  ".ruff_cache",
  ".pytest_cache",
  "dist",
  "build",
  "out",
  "coverage",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".turbo",
  ".cache",
  ".gradle",
  ".terraform",
  ".pnpm-store",
  ".tox",
  ".nox",
  ".eggs",
]);

/** Any hidden "*cache" directory is a cache, whatever tool named it. */
const HIDDEN_CACHE = /^\..*cache$/i;

/** Third-party code: the directory itself is structure, its contents are not. */
const VENDOR_DIRS = new Set(["vendor", "third_party", "thirdparty"]);

/** Lockfiles carry package-manager evidence (toolchain's job), nothing else. */
export const LOCKFILES = new Set([
  "bun.lock",
  "bun.lockb",
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "Cargo.lock",
  "poetry.lock",
  "uv.lock",
  "Pipfile.lock",
  "go.sum",
  "Gemfile.lock",
  "composer.lock",
]);

const GENERATED_MARKER = /@generated|code generated by|do not edit|automatically generated/i;
const SNIFF_BYTES = 1024;

export async function collectInventory(root: string): Promise<Inventory> {
  const files: InventoryFile[] = [];
  const dirs: string[] = [];
  const vendored: string[] = [];
  const denied: string[] = [];
  const lockfiles: string[] = [];
  // `target/` is Cargo build output only when a Cargo.toml says so.
  const denyTarget = await exists(join(root, "Cargo.toml"));

  /** Stack of .gitignore matchers, each scoped to the directory that declared it. */
  type Matcher = { dir: string; ig: Ignore };
  const matchers: Matcher[] = [];

  const isIgnored = (relPath: string, isDir: boolean): boolean => {
    const probe = isDir ? `${relPath}/` : relPath;
    return matchers.some(({ dir, ig }) => {
      const local =
        dir === "" ? probe : probe.startsWith(`${dir}/`) ? probe.slice(dir.length + 1) : "";
      return local !== "" && ig.ignores(local);
    });
  };

  const walk = async (relDir: string): Promise<void> => {
    const gitignore = await readIfExists(join(root, relDir, ".gitignore"));
    if (gitignore !== undefined) matchers.push({ dir: relDir, ig: ignore().add(gitignore) });

    const entries = await readdir(join(root, relDir), { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isSymbolicLink()) continue;
      const name = entry.name.normalize("NFC");
      const relPath = relDir === "" ? name : `${relDir}/${name}`;

      if (entry.isDirectory()) {
        if (DENY_DIRS.has(name) || HIDDEN_CACHE.test(name) || (name === "target" && denyTarget)) {
          if (name !== ".git") denied.push(relPath);
          continue;
        }
        if (isIgnored(relPath, true)) continue;
        dirs.push(relPath);
        if (VENDOR_DIRS.has(name.toLowerCase())) {
          vendored.push(relPath);
          continue;
        }
        await walk(relPath);
      } else if (entry.isFile()) {
        // Gitignore first: an ignored lockfile is absent from a fresh clone,
        // so counting it would break clone-state invariance (ADR-0003).
        if (isIgnored(relPath, false)) continue;
        if (LOCKFILES.has(name)) {
          lockfiles.push(relPath);
          continue;
        }
        const size = Bun.file(join(root, relPath)).size;
        if (await looksGenerated(join(root, relPath), size)) continue;
        files.push({ path: relPath, size });
      }
    }

    if (gitignore !== undefined) matchers.pop();
  };

  await walk("");
  files.sort((a, b) => comparePaths(a.path, b.path));
  for (const list of [dirs, vendored, denied, lockfiles]) list.sort(comparePaths);
  return { root, files, dirs, vendored, denied, lockfiles };
}

/** The inventory of one directory inside another's, paths made relative to it: the same eyes, narrowed. */
export function subInventory(inventory: Inventory, dir: string): Inventory {
  const prefix = `${dir}/`;
  const inside = (path: string) => path.startsWith(prefix);
  const strip = (path: string) => path.slice(prefix.length);
  return {
    root: join(inventory.root, dir),
    files: inventory.files
      .filter((f) => inside(f.path))
      .map((f) => ({ ...f, path: strip(f.path) })),
    dirs: inventory.dirs.filter(inside).map(strip),
    vendored: inventory.vendored.filter(inside).map(strip),
    denied: inventory.denied.filter(inside).map(strip),
    lockfiles: inventory.lockfiles.filter(inside).map(strip),
  };
}

/**
 * The shared "evidence files at repo root" view scanners key decisions on.
 * Lockfiles are deliberately excluded: they are toolchain-only evidence,
 * which the toolchain scanner merges in itself.
 */
export function rootFiles(inventory: { files: { path: string }[] }): Set<string> {
  return new Set(inventory.files.filter((f) => !f.path.includes("/")).map((f) => f.path));
}

/** Segment-wise path comparison, so enumeration order never leaks into output. */
export function comparePaths(a: string, b: string): number {
  const as = a.split("/");
  const bs = b.split("/");
  for (let i = 0; i < Math.min(as.length, bs.length); i++) {
    const sa = as[i] as string;
    const sb = bs[i] as string;
    if (sa !== sb) return sa < sb ? -1 : 1;
  }
  return as.length - bs.length;
}

async function looksGenerated(absPath: string, size: number): Promise<boolean> {
  if (size === 0 || size > 8 * 1024 * 1024) return false;
  const fd = await open(absPath, "r");
  try {
    const buffer = Buffer.alloc(Math.min(SNIFF_BYTES, size));
    const { bytesRead } = await fd.read(buffer, 0, buffer.length, 0);
    return GENERATED_MARKER.test(buffer.toString("latin1", 0, bytesRead));
  } finally {
    await fd.close();
  }
}

async function exists(absPath: string): Promise<boolean> {
  return Bun.file(absPath).exists();
}
