#!/usr/bin/env bun
/**
 * Writes packages/cli/src/ui.generated.ts: one file import per asset of the
 * built webview (apps/desktop/dist), so `bun build --compile` embeds the GUI
 * in the binary and `bun build --target=bun` copies it beside the npm entry.
 * The file is generated, never committed; a plain checkout serves the dist
 * directory instead: the daemon serves its own face.
 */
import { lstat, readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const cli = fileURLToPath(new URL("..", import.meta.url));
const dist = join(cli, "..", "..", "apps", "desktop", "dist");
const out = join(cli, "src", "ui.generated.ts");

const files: string[] = [];
for (const entry of await readdir(dist, { recursive: true })) {
  const rel = entry.replaceAll("\\", "/");
  if (rel.split("/").some((segment) => segment.startsWith("."))) continue; // a .DS_Store is not the GUI
  if ((await lstat(join(dist, rel))).isFile()) files.push(rel);
}
files.sort();
if (!files.includes("index.html")) {
  throw new Error(`No built webview at ${dist}; run \`bun run --cwd apps/desktop build\` first.`);
}

const lines = [
  "// Generated by packages/cli/scripts/embed-ui.ts from apps/desktop/dist; not committed.",
  "// @ts-nocheck",
  'import { isAbsolute } from "node:path";',
  'import { fileURLToPath } from "node:url";',
  ...files.map(
    (file, i) =>
      `import f${i} from "${relative(join(cli, "src"), join(dist, file)).replaceAll("\\", "/")}" with { type: "file" };`,
  ),
  "",
  "/** Embedded in a compiled binary, beside the entry when bundled, on disk in a plain run. */",
  "const at = (p: string): string => (isAbsolute(p) ? p : fileURLToPath(new URL(p, import.meta.url)));",
  "",
  "const files: Record<string, string> = {",
  ...files.map((file, i) => `  ${JSON.stringify(file)}: at(f${i}),`),
  "};",
  "",
  "export default files;",
  "",
];
await writeFile(out, lines.join("\n"));
console.log(`Embedded ${files.length} webview files into ${relative(process.cwd(), out)}.`);
